buy/urls.py
from django.urls import path
from . import views as buy_view
from bookBank import views as bookBank_view
urlpatterns = [
    path('',bookBank_view.index,name='buyBooks')
]

library/urls.py
from django.contrib import admin
from django.urls import path,include


from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('base.urls')),
    path('book-bank/',include('bookBank.urls')),
    path('buy',include('buy.urls')),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
else:
    urlpatterns += staticfiles_urlpatterns()
  

login/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views as login_view
urlpatterns = [
    path('',login_view.loginUser,name='login'),
    
]
 

social_django/urls.py
"""URLs module"""
from django.conf import settings
from django.conf.urls import url

from social_core.utils import setting_name
from . import views


extra = getattr(settings, setting_name('TRAILING_SLASH'), True) and '/' or ''

app_name = 'social'

urlpatterns = [
    # authentication / association
    url(r'^login/(?P<backend>[^/]+){0}$'.format(extra), views.auth,
        name='begin'),
    url(r'^complete/(?P<backend>[^/]+){0}$'.format(extra), views.complete,
        name='complete'),
    # disconnection
    url(r'^disconnect/(?P<backend>[^/]+){0}$'.format(extra), views.disconnect,
        name='disconnect'),
    url(r'^disconnect/(?P<backend>[^/]+)/(?P<association_id>\d+){0}$'
        .format(extra), views.disconnect, name='disconnect_individual'),
]

login/models.py
from django.db import models

# Create your models here.

login/views.py
from django.shortcuts import render,redirect
from .form import loginForm
from django.contrib.auth import login,authenticate
# Create your views here.
def loginUser(request):
    login_error = pass_error = " "
    if request.method == 'POST':
        print('****************************')
        form = loginForm(request.POST)
        if len(form.data['password']) < 8:
            pass_error = 'Please enter correct password'
            print('@@@@@@@@@@@@@@@@@@')
        else:
            print('$$$$$$$$$$$$$$$$$$$$')
            username = form.data['username']
            password = form.data['password']
            user = authenticate(username = username, password = password)
            if user and user.is_active :
                login(request,user)
                return redirect('dashboard')
            else:
                login_error = 'Please use correct username or password'
    else:
        print('------------------------')
        form = loginForm()
    return render(request,'login/login.html',{'form':form,'login_error':login_error,'pass_error':pass_error}) 

login/templates/login/login.html
{% extends 'base/base.html' %}

{% block page_title %} <title>Login</title> {% endblock %}

{% block container %}
<div >
    <div class="text-center" style="font-size: 40px;">
        Login
    </div>
    <div class="d-flex justify-content-end"><a href="{% url 'home' %}"><button class="btn btn-secondary">HOME</button></a></div>
    <div class="d-flex justify-content-center">
    <div style="display: flex; justify-content: center;flex-direction: column;">
        <div class="d-flex justify-content-center" style="text-decoration: none;font-size: 20px;font-family: Arial, Helvetica, sans-serif;">
            <div class="m-2">
                <a href=""><div class="btn" style="background-color: rgb(245, 32, 32);color: rgb(255, 255, 255);"><span></span> Google+</div></a>
            </div>
            <div class="m-2">
                <a href="{% url 'social:begin' 'facebook' %}"><div class="btn" style="background-color: blue; color: rgb(255, 255, 255);"><span></span> Facebook</div></a>
            </div>
            <div class="m-2">
                <a href=""><div class="btn" style="background-color: rgb(46, 200, 247); color: rgb(255, 255, 255);"><span></span> Twitter</div></a>
            </div>
            <div class="m-2">
                <a href="{% url 'social:begin' 'github' %}"><div class="btn" style="background-color: black; color: rgb(255, 255, 255);"><span></span> Github</div></a>
            </div>
        </div>
        <div>
            <form action="{% url 'login' %}" method="POST" style="width: 500px;" >
                {% csrf_token %}
                <br>
                {% if login_error != ' ' or pass_error != ' ' %}
                <small  class="alert alert-danger">{{ login_error }} <br> {{ pass_error }}</small>
                {% endif %}
                <div class="mt-3"></div>
                {% for field in form %}
                    <div class="form-group">
                        {{field.label_tag}}
                        {{ field }}
                        <ul>
                            {% for error in errors %}
                                <li style="color: red;"><small>{{error}}</small></li>
                            {% endfor %}
                        </ul>
                    </div>
                {% endfor %}
                <div class="text-center ">
                    <input type="submit" class="btn btn-primary" style="width: 80%;" value="LOGIN">
                </div>

            </form>
        </div>

    </div>
    </div>
    <p class="text-center">Do you have not created an account yet?<a href="{% url 'signup' %}" style="text-decoration:none">Signup</a></p>
    <p class="text-center"><a href="{% url 'resetPassword' %}" style="text-decoration:none">Forget Password</a></p>
</div>
{% endblock %}